site_title = "Arxiv Speech Papers"
limit_days = 15
cache_url = "https://Shayne-Ada.github.io/arxivpaper/cache.json"

[[sources]]
limit = 150
category = "cs.SD"
title = "Sound"

[[sources]]
limit = 150
category = "eess.AS"
title = "Audio and Speech Processing"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
